generate:
	oapi-codegen -generate types,chi-server,spec api/gophermart.yaml > api/gophermart.gen.go
	oapi-codegen -generate types,client api/accrual/accrual.yaml > api/accrual/accrual.gen.go

lint:
	golangci-lint run ./...
	staticcheck ./...

test:
	go fmt ./internal/...
	go vet ./internal/...
	go test -v ./internal/...
	#go test -v -race -count 100 ./internal/...
	#go test -gcflags=-l -count=1 -timeout=30s -bench=. -run=^$  ./internal/...
