// Package Accrual provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package Accrual

import (
	"context"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
)

// Defines values for ResponseStatus.
const (
	ResponseStatusINVALID ResponseStatus = "INVALID"

	ResponseStatusPROCESSED ResponseStatus = "PROCESSED"

	ResponseStatusPROCESSING ResponseStatus = "PROCESSING"

	ResponseStatusREGISTERED ResponseStatus = "REGISTERED"
)

// номер заказа
type Order int

// Response defines model for Response.
type Response struct {
	// рассчитанные баллы к начислению, при отсутствии начисления — поле отсутствует в ответе
	Accrual *int `json:"accrual,omitempty"`

	// номер заказа
	Order *Order `json:"order,omitempty"`

	// Статус расчёта начисления * `REGISTERED` - заказ зарегистрирован, но не начисление не рассчитано * `INVALID` - заказ не принят к расчёту, и вознаграждение не будет начислено. Конечный статус * `PROCESSING` - расчёт начисления в процессе * `PROCESSED` - расчёт начисления окончен. Конечный статус.
	Status *ResponseStatus `json:"status,omitempty"`
}

// Статус расчёта начисления * `REGISTERED` - заказ зарегистрирован, но не начисление не рассчитано * `INVALID` - заказ не принят к расчёту, и вознаграждение не будет начислено. Конечный статус * `PROCESSING` - расчёт начисления в процессе * `PROCESSED` - расчёт начисления окончен. Конечный статус.
type ResponseStatus string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetApiOrdersNumber request
	GetApiOrdersNumber(ctx context.Context, number Order, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetApiOrdersNumber(ctx context.Context, number Order, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiOrdersNumberRequest(c.Server, number)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetApiOrdersNumberRequest generates requests for GetApiOrdersNumber
func NewGetApiOrdersNumberRequest(server string, number Order) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "number", runtime.ParamLocationPath, number)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/orders/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetApiOrdersNumber request
	GetApiOrdersNumberWithResponse(ctx context.Context, number Order, reqEditors ...RequestEditorFn) (*GetApiOrdersNumberResponse, error)
}

type GetApiOrdersNumberResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Response
}

// Status returns HTTPResponse.Status
func (r GetApiOrdersNumberResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiOrdersNumberResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetApiOrdersNumberWithResponse request returning *GetApiOrdersNumberResponse
func (c *ClientWithResponses) GetApiOrdersNumberWithResponse(ctx context.Context, number Order, reqEditors ...RequestEditorFn) (*GetApiOrdersNumberResponse, error) {
	rsp, err := c.GetApiOrdersNumber(ctx, number, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiOrdersNumberResponse(rsp)
}

// ParseGetApiOrdersNumberResponse parses an HTTP response from a GetApiOrdersNumberWithResponse call
func ParseGetApiOrdersNumberResponse(rsp *http.Response) (*GetApiOrdersNumberResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiOrdersNumberResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
