openapi: "3.0.2"
info:
  title: Gophermart Loyalty Service
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /api/user/register:
    post:
      summary: Регистрация пользователя в программе лояльности
      description: >
        После успешной регистрации происходит автоматическая аутентификация пользователя через cookie.
      tags:
        - Регистрация и аутентификация
      requestBody:
        description: Параметры для регистрации
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
            example:
              login: userfoo
              password: p@sw0dr

      responses:
        '200':
          description: Пользователь успешно зарегистрирован и аутентифицирован
        '400':
          description: Неверный формат запроса
        '409':
          description: Логин уже занят
        '500':
          description: Внутренняя ошибка сервера

  /api/user/login:
    post:
      summary: Аутентификация пользователя
      description: Аутентификация производится по паре логин/пароль
      tags:
        - Регистрация и аутентификация
      requestBody:
        description: Параметры для авторизации
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
              example:
                login: userfoo
                password: p@sw0dr
      responses:
        '200':
          description: Пользователь успешно аутентифицирован
        '400':
          description: Неверный формат запроса
        '401':
          description: Неверная пара логин/пароль
        '500':
          description: Внутренняя ошибка сервера

  /api/user/orders:
    post:
      summary: Загрузка номера заказа
      tags:
        - Заказы
      requestBody:
        description: Номер заказа в Гофермаркете
        required: true
        content:
          text/plain:
            schema:
              description: Последовательность цифр произвольной длины
              type: integer
              example: 12345678903
      responses:
        '200':
          description: Номер заказа уже был загружен этим пользователем
        '202':
          description: Новый номер заказа принят в обработку
        '400':
            description: Неверный формат запроса
        '401':
            description: Пользователь не аутентифицирован
        '409':
            description: Номер заказа уже был загружен другим пользователем
        '422':
            description: Неверный формат номера заказа
        '500':
            description: Внутренняя ошибка сервера

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
      required:
        - login
        - password

    LoginRequest:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
      required:
        - login
        - password

