// Package Gophermart provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package Gophermart

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for OrderStatus.
const (
	OrderStatusINVALID OrderStatus = "INVALID"

	OrderStatusNEW OrderStatus = "NEW"

	OrderStatusPROCESSED OrderStatus = "PROCESSED"

	OrderStatusPROCESSING OrderStatus = "PROCESSING"
)

// Amount defines model for Amount.
type Amount float32

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// Order defines model for Order.
type Order struct {
	// Начисленные баллы. Может быть 0 или отсутствовать
	Accrual *float32 `json:"accrual,omitempty"`

	// Номер заказа
	Number string `json:"number"`

	// Статус обработки заказа
	Status OrderStatus `json:"status"`

	// Время загрузки заказа
	UploadedAt string `json:"uploaded_at"`
}

// Статус обработки заказа
type OrderStatus string

// OrdersResponse defines model for OrdersResponse.
type OrdersResponse []Order

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// UserBalanceResponse defines model for UserBalanceResponse.
type UserBalanceResponse struct {
	Current   Amount `json:"current"`
	Withdrawn Amount `json:"withdrawn"`
}

// UserBalanceWithdrawRequest defines model for UserBalanceWithdrawRequest.
type UserBalanceWithdrawRequest struct {
	Order *string `json:"order,omitempty"`
	Sun   *Amount `json:"sun,omitempty"`
}

// UserBalanceWithdrawJSONBody defines parameters for UserBalanceWithdraw.
type UserBalanceWithdrawJSONBody UserBalanceWithdrawRequest

// UserLoginJSONBody defines parameters for UserLogin.
type UserLoginJSONBody LoginRequest

// UserRegisterJSONBody defines parameters for UserRegister.
type UserRegisterJSONBody RegisterRequest

// UserBalanceWithdrawJSONRequestBody defines body for UserBalanceWithdraw for application/json ContentType.
type UserBalanceWithdrawJSONRequestBody UserBalanceWithdrawJSONBody

// UserLoginJSONRequestBody defines body for UserLogin for application/json ContentType.
type UserLoginJSONRequestBody UserLoginJSONBody

// UserRegisterJSONRequestBody defines body for UserRegister for application/json ContentType.
type UserRegisterJSONRequestBody UserRegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение текущего баланса пользователя
	// (GET /api/user/balance)
	GetUserBalance(w http.ResponseWriter, r *http.Request)
	// Запрос на списание средств
	// (POST /api/user/balance/withdraw)
	UserBalanceWithdraw(w http.ResponseWriter, r *http.Request)
	// Получение информации о выводе средств
	// (GET /api/user/balance/withdrawals)
	UserBalanceWithdrawals(w http.ResponseWriter, r *http.Request)
	// Аутентификация пользователя
	// (POST /api/user/login)
	UserLogin(w http.ResponseWriter, r *http.Request)
	// Получение списка загруженных номеров заказов
	// (GET /api/user/orders)
	GetUserOrders(w http.ResponseWriter, r *http.Request)
	// Загрузка номера заказа
	// (POST /api/user/orders)
	UploadOrder(w http.ResponseWriter, r *http.Request)
	// Регистрация пользователя в программе лояльности
	// (POST /api/user/register)
	UserRegister(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetUserBalance operation middleware
func (siw *ServerInterfaceWrapper) GetUserBalance(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserBalance(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UserBalanceWithdraw operation middleware
func (siw *ServerInterfaceWrapper) UserBalanceWithdraw(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserBalanceWithdraw(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UserBalanceWithdrawals operation middleware
func (siw *ServerInterfaceWrapper) UserBalanceWithdrawals(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserBalanceWithdrawals(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UserLogin operation middleware
func (siw *ServerInterfaceWrapper) UserLogin(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserLogin(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetUserOrders operation middleware
func (siw *ServerInterfaceWrapper) GetUserOrders(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserOrders(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UploadOrder operation middleware
func (siw *ServerInterfaceWrapper) UploadOrder(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadOrder(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UserRegister operation middleware
func (siw *ServerInterfaceWrapper) UserRegister(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserRegister(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/balance", wrapper.GetUserBalance)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/balance/withdraw", wrapper.UserBalanceWithdraw)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/balance/withdrawals", wrapper.UserBalanceWithdrawals)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/login", wrapper.UserLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/orders", wrapper.GetUserOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/orders", wrapper.UploadOrder)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/register", wrapper.UserRegister)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYX2/TVhT/Ktbd3hYaJ21H66fBQKhSBVPZxgOrJpPctmaJba5tSoUqJWkZTGHq/jzw",
	"sE0M7Qu4bUJD27hf4dxvNJ1jO3Ecp0kZYfDSOonvuefP7/zO797HrGRVbcvkpusw7TFzShu8qtPjlarl",
	"mS4+Vb2Ka9gVfmuNaeqMWsgxd8vmTGOmV73HBdvOsWVr3TBX+AOPO7TEFpbNhWtwMlXBX/EhWue4wjDX",
	"cZ2tO86mJcoZP27nmOAPPEPwMtPuRjYSK1Z7blj37vOSi+ZuiTIXw/vrpZLw9Ao+lrlTEobtGpbJNAZ/",
	"gS+fQkfW4QTa0IWubEJbgX3w4QROZHNGgT8hgNfQlg0F9mVTNuRzRVWgAyfQUSCQDVmXO/S3AQcQwAH4",
	"+A7LMf5Ir9oVzrR5Vc1NksToKcvLAE6hLWsKHIEPx+Dj/+QWbLF4eWGxODt3WWW54TQ7ru56ToblV7JB",
	"/u7IugIB7Msa+LCPYcExxpfazvSqWIub1++wHPtq5daX12/fXrp5g+XY0s1vrywvXet/ff0aVqjvYLhm",
	"yDPPrlh6mZe/190M936TNWjDqdwLPTmUNbkDR5mu9TYqqkX1UqF4qaB+XZjXCkVNLXymzmpqRmJSEIvy",
	"30vXoHcj8eascMe2TIdjAIbLq5ToTwVfYxr7JN9vsHzUXfkQpts9g7oQ+hZ+XuHrhuNy8f930jcOF1f1",
	"im6WeDK8QW9KnhA85Ijzwo2YZDvHNg13oyz0TXPSJSnX4w2TlsZ4fyd6cWRKrZgzhrvGu4ifKSfwK8Nc",
	"s8iy4RI0b1j2BhdVXbjKsrWlV9wt5TYXD40SZzn2kAsnhH1hRsXtLZubum0wjc3OqDNFqpi7QT7nddvI",
	"ew4X+XthlPjlOqfoMDYdG2ipjFtyN5EMhukMq0l2iqpKdbRMN6qjbtsVo0Tr8/cdy+wPhXGpyEIMZSHV",
	"0//IOpxBWz6DLvjY2Wna8cPePpM1CGQdfMzFnFrIoIeXEMCJfA5HMe9CGz8r0EUS9+FANiCQNejEb0AX",
	"jc2HUae5BrpE5LVoEOyRb/IZdGCfvJJ1pGA4oL8+1dzxqlVdbPV92ZFPaXkH2gq5cyx35E/QhkMI4rHi",
	"QxfDUuAs0/095Cl93UG8w6/9FWwVdxyqfD7uBEK25WRgIKMbWNhX3HGvWuWtaWAg3XdZUHjRLzPWjFJ8",
	"RtPYj3IYT2LMENvORu8Hh685tZgtNRRZR3zgvCUb0EIPwhEMgXwKXQjwHYRgK1QUZK+Yba8dYRFFyxtF",
	"7pIvp2gMrUeSIQ43HpXTwv/4WqYCS6D8VfJNaoCLAF+vOCPpLwOQ+Pr7ocFJWuCt0FpU57IBEVYedSm0",
	"CAKHBKhUet8t3sfRIHSgm8Dmj9AhBxU4kE1SzK1hbAwWvCd6YnpLuf0L4hb3kw3oyF3oYNpwI8wnJY48",
	"DvfqkFbfI/bFPz5urBDDHKKr+eg7ygTLZeBpOdJPFyPQnkDtiTiGwa1ZVlKKacz+wtlUy6QOJwPcwNEr",
	"C2IvKR6f6KAha7KpQAvnTLqiUW1YUnK5wuOT0e4o7ODRoofwQAE/XSwqVG2QP9UL892EjJ4wErZbWGx/",
	"JACmRZfnY3a8MPibNEUH+wXNxys7GQnuW04zKUlfZ5x2DA850+TM1DHq/fBki/iwK5vySa8hAjrEt3Ei",
	"f7SqM2b7XkrCU/Pr+H4Dw+2rgwAOkvogGBzML+IfZJOt4iEzW1/SKTk81J5Hiy5/5Obtim6koDGc3+g+",
	"pjWYYXSbAP9cITzvylqa36O34A2VlEZPM3k7UCjOzs1/fnlhUZ3tndgM0+XreB7PgF32zYuCSfsdArlL",
	"OTwlvjgm3LTfkj5HbBQWjm6e4GSonIr8GZscTkdQBrThNOyD4ogtD4hK+3hIhXlGMEZUNijmVNPJnSnT",
	"9ZhWm2SULL6zZEOLPhxOkPCPRrH3b9T8czwYyQgD00REl1fnKLVea6dkASajNjzRcJxF/S3r8kms33ok",
	"G6YOOnSoIsYjVfMWo1UhE+jCkVKyrB8MPvOdman+4iu6D0cApi8NL6QBs9M+ZQ14FKruxL6Jts0WMVNT",
	"iVn88EesBXuUcERH0T3ZmFo3jhB0o/CKbBy2xmFU2NPoGCP3krOSavnfVSP6ysVDUot3HzNPVJjGNlzX",
	"1vL5ilXSKxuW42oL6oLKtle3/w0AAP//lGiaXlYaAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
