// Package Gophermart provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package Gophermart

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for OrderStatus.
const (
	OrderStatusINVALID OrderStatus = "INVALID"

	OrderStatusNEW OrderStatus = "NEW"

	OrderStatusPROCESSED OrderStatus = "PROCESSED"

	OrderStatusPROCESSING OrderStatus = "PROCESSING"
)

// Amount defines model for Amount.
type Amount float32

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// Order defines model for Order.
type Order struct {
	// Начисленные баллы. Может быть 0 или отсутствовать
	Accrual *float32 `json:"accrual,omitempty"`

	// Номер заказа
	Number string `json:"number"`

	// Статус обработки заказа
	Status OrderStatus `json:"status"`

	// Время загрузки заказа
	UploadedAt string `json:"uploaded_at"`
}

// Статус обработки заказа
type OrderStatus string

// OrdersResponse defines model for OrdersResponse.
type OrdersResponse []Order

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// UserBalanceResponse defines model for UserBalanceResponse.
type UserBalanceResponse struct {
	Current   Amount `json:"current"`
	Withdrawn Amount `json:"withdrawn"`
}

// UserBalanceWithdrawRequest defines model for UserBalanceWithdrawRequest.
type UserBalanceWithdrawRequest struct {
	Order string `json:"order"`
	Sum   Amount `json:"sum"`
}

// UserBalanceWithdrawal defines model for UserBalanceWithdrawal.
type UserBalanceWithdrawal struct {
	Order       string `json:"order"`
	ProcessedAt string `json:"processed_at"`
	Sum         Amount `json:"sum"`
}

// UserBalanceWithdrawalsResponse defines model for UserBalanceWithdrawalsResponse.
type UserBalanceWithdrawalsResponse []UserBalanceWithdrawal

// UserBalanceWithdrawJSONBody defines parameters for UserBalanceWithdraw.
type UserBalanceWithdrawJSONBody UserBalanceWithdrawRequest

// UserLoginJSONBody defines parameters for UserLogin.
type UserLoginJSONBody LoginRequest

// UserRegisterJSONBody defines parameters for UserRegister.
type UserRegisterJSONBody RegisterRequest

// UserBalanceWithdrawJSONRequestBody defines body for UserBalanceWithdraw for application/json ContentType.
type UserBalanceWithdrawJSONRequestBody UserBalanceWithdrawJSONBody

// UserLoginJSONRequestBody defines body for UserLogin for application/json ContentType.
type UserLoginJSONRequestBody UserLoginJSONBody

// UserRegisterJSONRequestBody defines body for UserRegister for application/json ContentType.
type UserRegisterJSONRequestBody UserRegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение текущего баланса пользователя
	// (GET /api/user/balance)
	GetUserBalance(w http.ResponseWriter, r *http.Request)
	// Запрос на списание средств
	// (POST /api/user/balance/withdraw)
	UserBalanceWithdraw(w http.ResponseWriter, r *http.Request)
	// Получение информации о выводе средств
	// (GET /api/user/balance/withdrawals)
	UserBalanceWithdrawals(w http.ResponseWriter, r *http.Request)
	// Аутентификация пользователя
	// (POST /api/user/login)
	UserLogin(w http.ResponseWriter, r *http.Request)
	// Получение списка загруженных номеров заказов
	// (GET /api/user/orders)
	GetUserOrders(w http.ResponseWriter, r *http.Request)
	// Загрузка номера заказа
	// (POST /api/user/orders)
	UploadOrder(w http.ResponseWriter, r *http.Request)
	// Регистрация пользователя в программе лояльности
	// (POST /api/user/register)
	UserRegister(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetUserBalance operation middleware
func (siw *ServerInterfaceWrapper) GetUserBalance(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserBalance(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UserBalanceWithdraw operation middleware
func (siw *ServerInterfaceWrapper) UserBalanceWithdraw(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserBalanceWithdraw(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UserBalanceWithdrawals operation middleware
func (siw *ServerInterfaceWrapper) UserBalanceWithdrawals(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserBalanceWithdrawals(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UserLogin operation middleware
func (siw *ServerInterfaceWrapper) UserLogin(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserLogin(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetUserOrders operation middleware
func (siw *ServerInterfaceWrapper) GetUserOrders(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserOrders(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UploadOrder operation middleware
func (siw *ServerInterfaceWrapper) UploadOrder(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadOrder(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UserRegister operation middleware
func (siw *ServerInterfaceWrapper) UserRegister(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserRegister(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/balance", wrapper.GetUserBalance)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/balance/withdraw", wrapper.UserBalanceWithdraw)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/balance/withdrawals", wrapper.UserBalanceWithdrawals)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/login", wrapper.UserLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/orders", wrapper.GetUserOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/orders", wrapper.UploadOrder)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/register", wrapper.UserRegister)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RY3W7bxhJ+FWLPuTuKRcn2ic2rJk0QGDDiwmmbi9QoGGltM5VIZknFMQIDkuw0KZTC",
	"/bnIRVukQV+AtqVYsSX6FWbfqJjhjyiKsuU0SpMbm5K4s9/OfPPtt/uElayqbZncdB2mPWFOaZNXdXq8",
	"VrVqpotP1VrFNewKX1lnmjqjFnLM3bY505hZq97ngu3k2LK1YZir/GGNOzTEFpbNhWtwClXBX/EhHOe4",
	"wjA3cJytO86WJcoZP+7kmOAPa4bgZabdC2MkRqzFMKz7D3jJxXAroszF6Px6qSRqegUfy9wpCcN2Dctk",
	"GoM/wJPPoCsbcAod6ENftqCjwAF4cAqnsjWjwO/gwxvoyKYCB7Ilm/KFoirQhVPoKuDLpmzIXfrbhEPw",
	"4RA8fIflGH+sV+0KZ9q8quYmSWL4lIXShx50ZF2BY/DgBDz8n5yCLRavLiwWZ+euqiw3mmbH1d2akxH5",
	"tWwS3l3ZUMCHA1kHDw5wWXCC60tNZ9aqWIvbN++yHPtideXzm3fuLN2+xXJs6fbX15aXbgy+vnkDKzQA",
	"GIwZQVazK5Ze5uVvdTcD3i+yDh3oyf0AyZGsy104zoQWT1RUi+qVQvFKQf2yMK8Vippa+J86q6kZiUlR",
	"LMx/nK5hdGP55qxyx7ZMh+MCDJdXKdH/FXydaew/+UGD5cPuygc03YkD6kLo2/h5lW8YjsvFv99JXzlc",
	"XNcrulniyeUNoynVhOCBRpy33FBJdnJsy3A3y0LfMicdkoIeTZiMdAH6u+GLY1NqRZox2jXI9nfCGcQM",
	"IkyIL5CnSaHZwipxx4n7ZkrYUxNNvJTLt0R2RkZaBMEa5rpFazZcavhblr3JRVUXrrJsbesVd1u5w8Uj",
	"o8RZjj3iwgnEpDCjYjzL5qZuG0xjszPqTJH6wN0kfHndNvI1h4v8/QAJfrnBKcFYFh1laamMU3I3AZhh",
	"AoP1UpyiqlJ3WKYbdodu2xWjROPzDxzLHGy1l8hLnFPKQkop/5INOIOOfA598FAv02LuBYp5JuvgywZ4",
	"mIs5tZAhuq/Ah1P5Ao6j3Qw6+FmBPm6NHhzKJviyDt3oDehjsPlg1WkFhz5tj/Vwe90nbPI5dOGAUMkG",
	"bmxwSH89YqNTq1Z1sT3Asiuf0fAudBSCcyJ35Q/QgSPwo83agz4uS4GzTPj7qP76hoMMh58HI9gazjhS",
	"+XykL9SUlpPBgQzGsqCTuONet8rb0+BAWs2yqPByUGasGaX4jDyOF+Yw8jeYIbaTzd6Pjl9zajHbwCmy",
	"gfxAF0MxoI0IAmMDvnwGffDxHaRgO/BpFK+YHa8TchGt4FtF7hGWHgbD6KERi5YbGZBp8f/iWqYWlmD5",
	"6+Sb1ACXIb5eccbKX7bmfyAZzNpl3psiFtW5bFIE1UfHD22iwRGRKpXi98v5i6QQutBP8PN76BJABQ5l",
	"i84i7VF+DBc9tpORxKVg/4TcxflkE7pyD7qYNpwI80mJI8TBXF06Be2TAuMfDydWSGWOEGo+/I4ywXIZ",
	"nFoOnenlRDS2/rE9Zri4dctKmlyN2Z85W2qZfPdkpBs61GZR7BWtxyNJaMq6bCnQxr0mXdGwNixptFxR",
	"45NJ7zju4KEtZrivgJcuFhWqPqyh6qU1b0JVTwQJ2i0otjeWANOSzPM5e7E5+JN8RRf7BcNHI7sZCR5E",
	"TqspmWjnIv8YHB+nqZupA+qH0ck26WFftuTTuCF8uh7p4K78yTrPSO3jlAT3EW+imyNc7sAh+HCY9Aj+",
	"8Ob8MvpBttgaHuiyPSbdP6yEJ7Lxsujyx27eruhGihqj+Q1vutrDGUbYRPgXCvF5T9bT+h6+BW+ppLT1",
	"tJL3LoXi7Nz8/68uLKqz8aHNMF2+wUUm7bLvtBRM2q/gyz3KYY/04oR403lH+RwzUVA4utOD05FyKvJH",
	"bHLojZEM6EAv6IPimCkPSUoHfEgt84xojKxs0ppTTSd3pyzXF7TaJFvJ4ntLNrTpw9EECf9kXPvgrtI7",
	"B8FYRRjaTUR4LXiOU4tbO2ULMBn10R0Nt7Owv2VDPo38WyyyQeqgSwcrUjxyNe+wtSoUAiEcKyXL+s7g",
	"M9+Yme4vuvz8eAxg+jr2Uh4wO+1T9oDHgetOzJto22wTMzWXmKUPv0VeMJaEYzqO7svm1LpxjKEbx1dU",
	"46A1jsLC9sJjjNxP7pVUy3/uGhErF4/ILd57wmqiwjS26bq2ls9XrJJe2bQcV1tQF1S2s7bzdwAAAP//",
	"uSDr/LAbAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
